version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.111.3"
    
phases:
  install:
    runtimeVersions:
      docker: 20
    commands:                                                                 
      - make hugo
  build:
    commands:
      - make build
      - make deploy
  post_build:
    commands:
      - echo Build completed on `date`
